# Generated by Django 4.0.2 on 2022-02-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220202_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
