# Generated by Django 4.0.2 on 2022-03-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_enroll_email_alter_enroll_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='project_developer',
            field=models.BooleanField(default=False, verbose_name='project developer'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='project_manager',
            field=models.BooleanField(default=False, verbose_name='project manager'),
        ),
    ]
