# Generated by Django 4.0.2 on 2022-03-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_status_task_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='task',
        ),
    ]
