# Generated by Django 4.0.2 on 2022-03-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_task_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='user_type',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
