# Generated by Django 4.0.2 on 2022-03-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_enroll_user_type_alter_project_id_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='user_type',
            field=models.CharField(max_length=200),
        ),
    ]
