# Generated by Django 4.0.2 on 2022-03-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('in-progress', 'in-progress'), ('testing', 'testing')], default='pending', max_length=32),
        ),
    ]
