# Generated by Django 4.0.2 on 2022-03-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('head', models.CharField(max_length=200)),
                ('resolved', models.BooleanField()),
                ('task', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.task', to_field='title')),
                ('tester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.enroll', to_field='username')),
            ],
        ),
    ]
